### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by black-snow** [MSOpenTech/msa-auth-for-android#10]
What are the reasons for using assertions in the auth lib?

Here's what my lint check has to say about this:

> Assertions are not checked at runtime. There are ways to request that they be used by Dalvik (adb shell setprop debug.assert 1), but the property is ignored in many places and can not be relied upon. Instead, perform conditional checking inside if (BuildConfig.DEBUG) { } blocks. That constant is a static final boolean which is true in debug builds and false in release builds, and the Java compiler completely removes all code inside the if-body from the app.
> 
> For example, you can replace assert speed > 0 with if (BuildConfig.DEBUG && !(speed > 0)) { throw new AssertionError() }.

**Comment by peternied** [comment]
The assertions are there from the legacy codebase that this library comes from.  At this time we are not planning on spending the effort to remove them.
