### ISSUE TITLE
minSdkVersion 15 => 14

### ISSUE THREAD

**Issue by black-snow** [MSOpenTech/msa-auth-for-android#15]
Hey, it's me again.

I didn't scan through the code but is there a reason for targetting sdk version 15 instead of 14? Both are ICS. Taking a quick look at the release notes I didn't see a difference in APIs.
I was targeting _minSdkVersion_ 14 in my project. When I switch to msa-auth (0.8.2) I can't compile anymore. It's complaining that I can't have _minSdkVersion_ 14 because msa-auth has 15. Although the difference is small I'd rather like not to raise my _minSdkVersion_.

Could you check _if_ there's troublesome code that won't work on 14 and:
- if yes, outline that code (so I can file a PR)
- if no, lower the requirement?

I started using the auth-part from the android picker example before it switched to msa-auth. I was using it on API level 14 without issues.

**Comment by peternied** [comment]
@black-snow I'm comfortable with accepting a pull request that changes the gradle build files to support API14.  The versioning target of this library was arbitrary.

**Comment by black-snow** [comment]
Alright. Tomorrow I'll check if there are any incompatibilities and then file a PR.

**Comment by black-snow** [comment]
PR filed here: https://github.com/MSOpenTech/msa-auth-for-android/pull/16
