### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by marcote** [MSOpenTech/msa-auth-for-android#2]
Enable Travis CI

**Comment by iambmelt** [comment]
Cool, I can pick this up :+1:

**Comment by iambmelt** [comment]
@marcote Just fyi I can't throw the lever to enable travis integration since I'm not a group member for MSOpenTech. If you do and it turns out that the `.travis.yml` has an issue ping me and I can investigate.

**Comment by marcote** [comment]
@iambmelt I can't do it either. @joshgav was working on that yesterday, not sure if Travis is already listening this repo.

**Comment by joshgav** [comment]
Yes it's listening but needed a new commit to trigger. I added the Travis badge to the README and committed and it's building now - ah, just reported success! Now just need to add some tests... :)
