### ISSUE TITLE
ANR when user selects `No` when asked for permissions

### ISSUE THREAD

**Issue by iambmelt** [MSOpenTech/msa-auth-for-android#32]
Parent issue: [microsoftgraph/msgraph-sdk-android/issues/20](https://github.com/microsoftgraph/msgraph-sdk-android/issues/20)

Filed by: @diogowbrito

See parent issue for description + steps to repro

This issue appears to be caused by [this check](https://github.com/OfficeDev/msa-auth-for-android/blob/master/src/main/java/com/microsoft/services/msa/AuthorizationRequest.java#L140-L142) inside the [newly 23 deprecated] [WebViewClient#onReceivedError](https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedError%28android.webkit.WebView, int, java.lang.String, java.lang.String%29).

Debug snapshot at [AuthorizationRequest.java#L140](https://github.com/OfficeDev/msa-auth-for-android/blob/master/src/main/java/com/microsoft/services/msa/AuthorizationRequest.java#L140)
![screen shot 2016-07-01 at 10 20 08 am](https://cloud.githubusercontent.com/assets/990063/16529441/bb7ad97e-3f77-11e6-8b46-c6b4131492a5.png)

**Comment by iambmelt** [comment]
After some more investigation, this appears to be infinite looping [here](https://github.com/OfficeDev/msa-auth-for-android/blob/master/src/main/java/com/microsoft/services/msa/AuthorizationRequest.java#L496-L504)

**Comment by ronnafaye** [comment]
Any update on this issue?

**Comment by iambmelt** [comment]
Hi @PAYong -- `msa-auth-for-android` is no longer under active maintenance. Please see [`AzureAD/microsoft-authentication-library-for-android`](https://github.com/azuread/microsoft-authentication-library-for-android) for our latest MSA/AzureAD auth solution
