### ISSUE TITLE
Expose the LiveConnectSession directly

### ISSUE THREAD

**Issue by peternied** [MSOpenTech/msa-auth-for-android#5]
If you want to just get the current instance of the session's authentication token, there is no builtin way but to hold a reference in app, we could just make this variable public to ease the burden on app developers https://github.com/MSOpenTech/msa-auth-for-android/blob/dev/src/main/java/com/microsoft/services/msa/LiveAuthClient.java#L513

**Comment by joshgav** [comment]
Thanks Peter, we won't be addressing these items ourselves at this time but would be happy to review and accept a PR.
