### ISSUE TITLE
1 to 1 relationship between LiveAuthClient & LiveConnectSession prompts for consent

### ISSUE THREAD

**Issue by iambmelt** [MSOpenTech/msa-auth-for-android#6]
If I'm understanding it correctly, it appears that in order to successfully make calls to `loginSilent()` the same `LiveAuthClient` which _originally_ called `login()` must be used to make the request.

What's the expected behavior between app / device restarts? At a glance, it would seem that if the user restarts their device or closes the app then they have to grant consent again because a new instance of `LiveAuthClient` has been instantiated.

Am I understanding this correctly? I'd prefer if users didn't have to grant consent every time they close the app or restart their devices.

**Comment by iambmelt** [comment]
The relevant code can be found [here](https://github.com/MSOpenTech/msa-auth-for-android/blob/dev/src/main/java/com/microsoft/services/msa/LiveConnectSession.java#L50).

**Comment by joshgav** [comment]
Hi @iambmelt, if you'd like to submit a pull request to address this issue we'd be happy to review it. We won't be addressing enhancement requests ourselves at this time for this repo. Thanks!

//cc @marcote

**Comment by iambmelt** [comment]
Ok thanks @joshgav :+1:
