### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by black-snow** [MSOpenTech/msa-auth-for-android#9]
Hi there,

are there any plans on replacing deprecated packages / classes such as `org.apache.http.NameValuePair` and `org.apache.http.client.HttpClient`?

**Comment by peternied** [comment]
No plans at this time

**Comment by black-snow** [comment]
Shouldn't this be left open as those things can be removed in future versions and thus breaking msa-auth on future android versions?

**Comment by black-snow** [comment]
@peternied Can't compile for **sdk version 23** as `org.apache.http.client` (and more) were removed.

**Comment by peternied** [comment]
@black-snow Can you import the gradle dependency use it in that way?

**Comment by black-snow** [comment]
Sadly no, I have some tiny changes in the code. Also see https://github.com/OneDrive/onedrive-explorer-android/issues/57
The only change I took to the old AuthClient was to deactivate the code that took the cookie from the prefs. This is what I currently have in there (`AuthClient.logout()`):

``` java
// deactivated as this allows re-login w\ prompt
//        final List<String> cookieKeys = this.getCookieKeysFromPreferences();
//        for (final String cookieKey : cookieKeys) {
//            final String value = TextUtils.join("", new String[]{
//                    cookieKey,
//                    "=; expires=Thu, 30-Oct-1980 16:00:00 GMT;domain=",
//                    domain,
//                    ";path=/;version=1"
//            });
//
//            manager.setCookie(url, value);
//        }
// clear cookies so that on login we get the prompt
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
    manager.removeAllCookies(null);
else
    manager.removeAllCookie();
```

If you added a switch to clear that cookie on logout I could switch back to your original code. (Which would leave me with just the issue I mentioned above)

Aside from all of this - would it actually work on platforms with versions _ge_ 23 if I used your lib via gradle? The mentioned stuff was removed in 23. Is e. g. `org.apache.http.client` somehow automagically
included then? Wouldn't it break anyhow?

**Comment by black-snow** [comment]
I've filed a pull request here: https://github.com/MSOpenTech/msa-auth-for-android/pull/14 - let's move that discussion there. (also targeted the dev branch this time)

My last question is still valid, though.

**Comment by peternied** [comment]
I tested this out a little yesterday just to confirm the documentation from Android,  you can still build a library than contains the Apache http libs in API23+, you just need to update the build scripts to allow for the legacy library ala:

``` gradle
android {
    useLibrary 'org.apache.http.legacy'
}
```

From: http://stackoverflow.com/a/32474095/533057

I've confirmed that a compiled AAR works just fine on a API23 device, so its just a matter of updating the build scripts if you upgrade to targeting API23

**Comment by black-snow** [comment]
Alright, I'll give it a shot tomorrow.
Still, there's a reason why those things are being deprecated. Maybe I'll file a PR with a "fix" some time. I'll report back how your solution works out for me. Thanks so far!

**Comment by black-snow** [comment]
Aight it's compiling. But now I have it at my top level gradle file. Shouldn't this be added to
https://github.com/MSOpenTech/msa-auth-for-android/blob/master/build.gradle ?

Thanks for the research work!

**Comment by peternied** [comment]
If we were targeting API23 in this project then yes, since we build this project and distribute via gradle the only reason to update would be to add new features/compatiblity
